import { useState, useMemo, useEffect } from "react";

const CATEGORIES = ["All", "Housing", "Metro Station"];

const PROJECTS = [
  // ── HOUSING ──────────────────────────────────────────────────────────────
  { id: 1, category: "Housing", name: "Quinta Monroy Housing", architect: "Elemental (Alejandro Aravena)", year: "2004", location: "Iquique, Chile", typology: "Social Housing", style: "Incremental / Contemporary", units: "93", total_area: "3,500 sqm", floors: "2", concept: "Each family received half a well-built house — the structurally complex half — with space designed for self-build expansion. The project reframes social housing as an investment framework, not a welfare product.", key_design_moves: ["Shared party walls reduce construction cost per unit", "Structural frame pre-built for future vertical expansion", "Dense urban infill maintains city connectivity"], materials: ["Reinforced concrete", "Masonry block", "Corrugated metal"], site_strategy: "Dense urban plot within existing city fabric, preserving resident proximity to jobs and services rather than relocating to periphery.", program: "93 residential units with shared open space and incremental expansion provision", awards: "Pritzker Architecture Prize 2016 (Aravena)", tags: ["incremental", "social", "latin america", "affordable", "self-build"], drawings: "N/A", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Quinta+Monroy" }, { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Quinta_Monroy" }], wiki: "Quinta_Monroy", last_updated: "2025-01-10" },
  { id: 2, category: "Housing", name: "Tietgen Dormitory", architect: "Lundgaard & Tranberg Arkitekter", year: "2006", location: "Copenhagen, Denmark", typology: "Student Housing", style: "Contemporary / Circular", units: "360", total_area: "24,700 sqm", floors: "7", concept: "A circular building form mediates between the individual and the collective — private rooms face outward to the city while shared kitchens and terraces project inward to a communal courtyard, creating layered social thresholds.", key_design_moves: ["Circular plan creates strong collective identity", "Projecting communal volumes break the ring's regularity", "Inward courtyard acts as shared social heart"], materials: ["Brick", "Copper", "Concrete", "Timber"], site_strategy: "Placed at the edge of a new university district, the circular form creates a landmark while its courtyard provides sheltered semi-public space.", program: "360 student rooms, communal kitchens per floor, music rooms, gym, common hall", awards: "Nominated Mies van der Rohe Award 2007", tags: ["circular", "collective", "student", "nordic", "courtyard"], drawings: "N/A", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Tietgen+Dormitory" }, { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Tietgen_Dormitory" }], wiki: "Tietgen_Dormitory", last_updated: "2025-01-10" },
  { id: 3, category: "Housing", name: "Habitat 67", architect: "Moshe Safdie", year: "1967", location: "Montreal, Canada", typology: "Experimental Collective Housing", style: "Brutalist / Modular", units: "158", total_area: "37,161 sqm", floors: "12", concept: "A utopian vision to combine the qualities of a suburban house — garden, privacy, fresh air — with the density and urban connectivity of an apartment building, achieved through stacking prefabricated concrete modules.", key_design_moves: ["354 prefabricated concrete boxes assembled in 3D array", "Each unit's roof becomes the next unit's garden terrace", "Pedestrian streets and bridges thread through the structure"], materials: ["Precast concrete", "Steel connections", "Glass"], site_strategy: "Built on a pier extending into the St. Lawrence River for Expo 67, creating a dense urban village on the waterfront.", program: "158 residential units ranging from 1 to 4 bedrooms, gardens, communal amenities", awards: "National Historic Site of Canada 2009", tags: ["brutalist", "modular", "prefab", "iconic", "experimental", "terrace"], drawings: "N/A", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Habitat+67" }, { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Habitat_67" }], wiki: "Habitat_67", last_updated: "2025-01-10" },
  { id: 4, category: "Housing", name: "8 House", architect: "BIG — Bjarke Ingels Group", year: "2010", location: "Copenhagen, Denmark", typology: "Mixed-Use Residential", style: "Contemporary / Parametric", units: "476", total_area: "61,000 sqm", floors: "10", concept: "Two loops of housing interlock in a figure-eight plan, creating a continuous sloping promenade from street level to the rooftop. The form combines the density of a city block with the intimacy of a townhouse neighbourhood.", key_design_moves: ["Figure-8 plan creates two distinct courtyard identities", "Continuous sloping bike and pedestrian path from ground to roof", "Ground floor commercial activates street edges"], materials: ["Brick", "Glass", "Steel", "Concrete"], site_strategy: "Located in Orestad, a new district south of Copenhagen, the building creates its own urban scale and internal street life in an otherwise sparse suburban context.", program: "476 apartments, penthouses, commercial units, offices at ground level", awards: "World Architecture Festival — Best Residential Building 2011", tags: ["mixed-use", "figure-eight", "nordic", "BIG", "promenade", "rooftop"], drawings: "N/A", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=8+House+BIG" }, { label: "BIG", url: "https://big.dk/projects/8-house" }], wiki: "8_House", last_updated: "2025-01-10" },
  { id: 5, category: "Housing", name: "Silodam", architect: "MVRDV", year: "2003", location: "Amsterdam, Netherlands", typology: "Mixed-Use Residential", style: "Contemporary / Colourful", units: "157", total_area: "17,000 sqm", floors: "10", concept: "A city within a building — Silodam stacks diverse housing typologies, tenures and sizes in a grid of neighbourhoods, each with its own identity expressed through facade colour and material. The mix replicates urban diversity in a single structure.", key_design_moves: ["Grid of mini neighbourhoods each with distinct facade treatment", "Mixed tenure — social, private, live-work — within one structure", "Public walkways and shared decks thread through the building"], materials: ["Steel", "Timber", "Glass", "Aluminium cladding"], site_strategy: "Cantilevered over the IJ waterway on a former industrial pier, the building reads as a moored vessel and activates Amsterdam's western docklands.", program: "157 units across 8 housing typologies, live-work units, communal spaces, commercial", awards: "Not Available", tags: ["mixed-use", "MVRDV", "waterfront", "colourful", "amsterdam"], drawings: "N/A", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Silodam+MVRDV" }, { label: "MVRDV", url: "https://www.mvrdv.nl/projects/111/silodam" }], wiki: "Silodam", last_updated: "2025-01-10" },
  { id: 6, category: "Housing", name: "Nakagin Capsule Tower", architect: "Kisho Kurokawa", year: "1972", location: "Tokyo, Japan", typology: "Capsule / Experimental Housing", style: "Metabolist", units: "140", total_area: "3,091 sqm", floors: "13", concept: "The physical embodiment of Japanese Metabolism — replaceable prefabricated capsules plugged onto two concrete service cores, theorising a city of interchangeable parts that could be updated without demolishing the whole.", key_design_moves: ["140 capsules bolted independently to concrete shafts", "Each capsule prefabricated off-site and crane-installed", "Design anticipates capsule replacement every 25 years"], materials: ["Precast concrete", "Corten steel capsule shells", "Porthole windows"], site_strategy: "Located in Shimbashi, Tokyo's salarymen district, the tower served as pied-a-terre units for workers staying in the city during the week.", program: "140 single-occupancy capsule units, each 10 sqm with built-in appliances", awards: "Designated culturally significant prior to demolition in 2022", tags: ["metabolism", "capsule", "japan", "iconic", "experimental", "prefab"], drawings: "N/A", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Nakagin+Capsule+Tower" }, { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Nakagin_Capsule_Tower" }], wiki: "Nakagin_Capsule_Tower", last_updated: "2025-01-10" },
  { id: 7, category: "Housing", name: "Golden Lane Estate", architect: "Chamberlin, Powell and Bon", year: "1962", location: "London, United Kingdom", typology: "Public Housing / Estate", style: "Brutalist", units: "559", total_area: "Not Available", floors: "16", concept: "A post-war vision of civilised urban living for working people — the estate combines high-rise and low-rise blocks around generously landscaped courts, with elevated walkways creating a pedestrian city above street level.", key_design_moves: ["Mix of 16-storey tower and lower perimeter blocks", "Elevated pedestrian deck links all buildings", "Community facilities including pool and sports hall embedded in estate"], materials: ["Reinforced concrete", "Brick", "Glass curtain wall"], site_strategy: "Built on a blitzed site in the City of London fringe, the estate introduced residential density adjacent to the financial district.", program: "559 residential units, community centre, swimming pool, sports facilities, nursery", awards: "Grade II* Listed Building", tags: ["brutalist", "public housing", "london", "post-war", "listed"], drawings: "N/A", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Golden+Lane+Estate" }, { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Golden_Lane_Estate" }], wiki: "Golden_Lane_Estate", last_updated: "2025-01-10" },
  { id: 8, category: "Housing", name: "Carabanchel Social Housing", architect: "Foreign Office Architects (FOA)", year: "2007", location: "Madrid, Spain", typology: "Social Housing", style: "Contemporary / Parametric", units: "100", total_area: "14,000 sqm", floors: "6", concept: "A perforated bamboo screen wraps the entire building facade, acting as a climatic filter that provides solar shading and privacy while maintaining ventilation — a low-tech ecological strategy embedded in a high-density urban block.", key_design_moves: ["Continuous bamboo screen as climatic and aesthetic envelope", "Sliding screen panels allow residents to control privacy and light", "Courtyard block typology adapted for Mediterranean climate"], materials: ["Bamboo", "Concrete", "Glass", "Steel"], site_strategy: "Inserted into the Carabanchel social housing development on Madrid's southern periphery, the bamboo facade creates identity within a repetitive urban fabric.", program: "100 social housing units with communal courtyard and ground floor amenities", awards: "Not Available", tags: ["social", "facade", "bamboo", "mediterranean", "FOA"], drawings: "N/A", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Carabanchel+Housing" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=Carabanchel+Housing" }], wiki: "Foreign_Office_Architects", last_updated: "2025-01-10" },
  { id: 9, category: "Housing", name: "Monterrey Housing", architect: "Elemental (Alejandro Aravena)", year: "2010", location: "Monterrey, Mexico", typology: "Social Housing", style: "Incremental / Contemporary", units: "70", total_area: "Not Available", floors: "2", concept: "A second application of Elemental's half-a-house strategy adapted to a Mexican context — families occupy one half of a two-storey structure with structural provisions enabling them to complete the other half over time.", key_design_moves: ["Half-built party wall structure enables self-completion", "Open ground floor framing allows flexible future infill", "Dense site layout maximises unit count within budget"], materials: ["Reinforced concrete", "Masonry", "Steel frame"], site_strategy: "Urban infill site within the city, maintaining resident access to existing urban networks and employment.", program: "70 incremental residential units with self-build expansion capacity", awards: "Not Available", tags: ["incremental", "social", "mexico", "affordable", "elemental"], drawings: "N/A", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Monterrey+Housing+Elemental" }], wiki: "Elemental_(architecture_firm)", last_updated: "2025-01-10" },
  { id: 10, category: "Housing", name: "Wohnpark Neue Donau", architect: "Adolf Krischanitz", year: "1997", location: "Vienna, Austria", typology: "Urban Residential", style: "Contemporary / Minimalist", units: "220", total_area: "Not Available", floors: "8", concept: "A precisely ordered housing complex along the Neue Donau waterfront, where repetitive yet carefully proportioned facades create a coherent urban edge while internal organisation maximises views and cross-ventilation for every unit.", key_design_moves: ["Linear blocks oriented perpendicular to waterfront for view access", "Consistent facade rhythm with subtle variation in balcony depth", "Ground floor public path maintains waterfront permeability"], materials: ["Render", "Concrete", "Aluminium windows", "Timber balconies"], site_strategy: "Positioned along the Neue Donau leisure waterway, the project forms part of Vienna's coordinated waterfront residential development strategy.", program: "220 residential units with ground floor commercial and direct waterfront access", awards: "Not Available", tags: ["waterfront", "vienna", "minimalist", "urban edge"], drawings: "N/A", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Wohnpark+Neue+Donau" }], wiki: "Adolf_Krischanitz", last_updated: "2025-01-15" },

  // ── METRO STATIONS ───────────────────────────────────────────────────────
  { id: 11, category: "Metro Station", name: "Bilbao Metro", architect: "Norman Foster", year: "1995", location: "Bilbao, Spain", typology: "Underground Metro Station", style: "High-Tech / Contemporary", units: "N/A", total_area: "Various per station", floors: "B3", concept: "Nicknamed 'Fosteritos', the station entrances are iconic glass and steel canopies that emerge from the ground like transparent shells. Below ground, a single cavernous vault in reinforced concrete eliminates intermediate columns, creating a clear, legible station environment.", key_design_moves: ["Single-vault concrete shell eliminates platform columns", "Glazed entrance canopies as urban landmarks", "Consistent modular system repeated across all 40 stations"], materials: ["Reinforced concrete", "Structural glass", "Steel", "Granite"], site_strategy: "Stations designed as a coherent family across the whole Bilbao network, using consistent architectural language to create a unified passenger experience throughout the city.", program: "40 stations with platform, concourse, ticketing, and entrance pavilions", awards: "RIBA Award 1998", tags: ["underground", "foster", "vault", "high-tech", "bilbao", "spain"], drawings: "Plans and sections available on Archdaily and Divisare", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Bilbao+Metro+Foster" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=Bilbao+Metro" }, { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Bilbao_metro" }], wiki: "Bilbao_metro", last_updated: "2025-01-15" },
  { id: 12, category: "Metro Station", name: "Toledo Metro Station", architect: "Oscar Tusquets Blanca", year: "2012", location: "Naples, Italy", typology: "Underground Metro Station", style: "Contemporary / Art-Integrated", units: "N/A", total_area: "6,000 sqm", floors: "B4", concept: "Described as the deepest and most spectacular station in Europe, Toledo integrates immersive art installations with architecture. The station descends 50 metres through a wave-patterned mosaic tunnel, with William Kentridge's mosaic murals covering the entire concourse walls.", key_design_moves: ["Mosaic-clad wave tunnel creates immersive descent", "Natural light drawn 40m underground via central oculus", "Art fully integrated into architecture — not applied as decoration"], materials: ["Glass mosaic tiles", "Concrete", "Steel", "Backlit panels"], site_strategy: "Part of Naples' 'Art Stations' programme, transforming each metro station into a cultural destination commissioned to different architects and artists.", program: "Platform, concourse, ticketing hall, integrated art installation", awards: "Best Station in the World — Tube Lines Award 2013", tags: ["art station", "naples", "underground", "mosaic", "landmark", "italy"], drawings: "Section drawings available on Archdaily", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Toledo+Metro+Station+Naples" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=Toledo+Metro+Naples" }, { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Toledo_(Naples_Metro)" }], wiki: "Toledo_(Naples_Metro)", last_updated: "2025-01-15" },
  { id: 13, category: "Metro Station", name: "King Abdullah Financial District Metro Station", architect: "Zaha Hadid Architects", year: "2024", location: "Riyadh, Saudi Arabia", typology: "Elevated Metro Station", style: "Parametric / Contemporary", units: "N/A", total_area: "15,000 sqm", floors: "3", concept: "The station's perforated steel facade is derived from geometric Islamic patterns, creating a continuous skin of triangulated apertures that filter desert light into the interior while establishing a distinct urban landmark on Riyadh's skyline.", key_design_moves: ["Triangulated perforated facade filters solar gain and creates identity", "Flowing interior concourse inspired by desert landscape formations", "Integrated structural skin — facade and structure are one system"], materials: ["Perforated steel panels", "Concrete", "Glass", "Aluminium"], site_strategy: "Anchor station for the KAFD business district, designed as a gateway landmark connecting the metro to one of Riyadh's most significant new urban developments.", program: "Concourse, platforms, passenger facilities, retail, interchange connections", awards: "Part of Riyadh Metro — World's Longest Driverless Network", tags: ["ZHA", "parametric", "riyadh", "elevated", "saudi", "facade", "islamic"], drawings: "Facade details and plans on Archdaily and Dezeen", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=KAFD+Metro+Station+Zaha+Hadid" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=KAFD+Metro+Zaha+Hadid" }, { label: "ZHA", url: "https://www.zaha-hadid.com/architecture/king-abdullah-financial-district-metro-station/" }], wiki: "Zaha_Hadid_Architects", last_updated: "2025-01-15" },
  { id: 14, category: "Metro Station", name: "Qasr AlHokm Metro Station", architect: "Snøhetta", year: "2019", location: "Riyadh, Saudi Arabia", typology: "Underground Metro Station", style: "Contemporary / Sculptural", units: "N/A", total_area: "12,000 sqm", floors: "B2", concept: "A mirrored bowl-shaped canopy at street level reflects the sky and its surroundings, making the station entrance almost invisible while revealing a subterranean planted atrium below. The concept draws on the local tradition of shaded outdoor spaces and water features.", key_design_moves: ["Mirrored canopy reflects sky — station disappears into urban fabric", "Underground planted atrium brings biophilic quality to transit", "Geometry derived from traditional Islamic muqarnas vaulting"], materials: ["Mirrored steel canopy", "Stone", "Concrete", "Planted walls"], site_strategy: "Located adjacent to the historic Qasr AlHokm Palace, the station design responds to the cultural and historic significance of its context through material restraint and reference to Islamic spatial traditions.", program: "Platform, concourse, ticketing, planted atrium, street-level pavilion", awards: "Not Available", tags: ["snohetta", "riyadh", "underground", "biophilic", "mirrored", "islamic"], drawings: "Section and concept drawings on Divisare and Dezeen", sources: [{ label: "Dezeen", url: "https://www.dezeen.com/?s=Qasr+AlHokm+Metro+Station" }, { label: "Divisare", url: "https://divisare.com/search?q=Snohetta+Metro+Riyadh" }, { label: "Snohetta", url: "https://snohetta.com/projects/qasr-alhokm-metro-station" }], wiki: "Snohetta_(company)", last_updated: "2025-01-15" },
  { id: 15, category: "Metro Station", name: "Stadelhofen Station", architect: "Santiago Calatrava", year: "1990", location: "Zurich, Switzerland", typology: "Rail / Metro Station", style: "Structural Expressionism", units: "N/A", total_area: "N/A", floors: "3 levels", concept: "Calatrava's first major public commission — the station extends along a curved hillside, with a spine of branching steel ribs that support the platform canopy. The structural system is exposed as architecture, referencing the form of a skeleton or tree canopy.", key_design_moves: ["Branching steel rib structure as primary architectural element", "Three-level section carved into hillside topography", "Retail gallery integrated into the lower concourse level"], materials: ["Steel", "Concrete", "Glass", "Stone"], site_strategy: "Carved into a hillside adjacent to Zurich's old town, the station follows a curved alignment while three parallel levels — platforms, concourse, and retail — step down the slope.", program: "2 platforms, concourse level, commercial gallery, pedestrian connections", awards: "Awarded Heinrich Tessenow Medal", tags: ["calatrava", "zurich", "structural expressionism", "steel", "curved", "hillside"], drawings: "Structural drawings and sections widely published — Archdaily and Divisare", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Stadelhofen+Station+Calatrava" }, { label: "Divisare", url: "https://divisare.com/search?q=Stadelhofen+Calatrava" }, { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Stadelhofen_railway_station" }], wiki: "Stadelhofen_railway_station", last_updated: "2025-01-15" },
  { id: 16, category: "Metro Station", name: "Canary Wharf Station", architect: "Norman Foster", year: "1999", location: "London, United Kingdom", typology: "Underground Metro Station", style: "High-Tech / Contemporary", units: "N/A", total_area: "30,000 sqm", floors: "B5", concept: "An enormous glass and steel egg-shaped entrance canopy marks the station above ground, while below, a series of escalators descend through a layered underground concourse to the Jubilee Line platforms located 28 metres below Canary Wharf dock.", key_design_moves: ["Glazed egg canopy as iconic urban marker", "Series of escalator voids create spatial drama during descent", "Structural glass roof spans dock — station visible from water"], materials: ["Structural glass", "Steel", "Concrete", "Granite"], site_strategy: "Positioned beneath West India Quay in Canary Wharf, the station is part of the Jubilee Line Extension — one of the most architecturally ambitious transit projects in UK history.", program: "5-level underground station, platforms, ticketing, concourse, retail", awards: "Part of Jubilee Line Extension — RIBA Award 1999", tags: ["foster", "london", "jubilee line", "underground", "glass canopy", "canary wharf"], drawings: "Full section drawings on Archdaily and Wikipedia", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Canary+Wharf+Station+Foster" }, { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Canary_Wharf_tube_station" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=Canary+Wharf+tube+station" }], wiki: "Canary_Wharf_tube_station", last_updated: "2025-01-15" },
  { id: 17, category: "Metro Station", name: "Elizabeth Line — Paddington Station", architect: "Grimshaw Architects", year: "2022", location: "London, United Kingdom", typology: "Underground Metro Station", style: "Contemporary / Engineered", units: "N/A", total_area: "Various", floors: "B3", concept: "The Elizabeth Line stations redefine the underground experience through consistent material quality, generous proportions, and integrated wayfinding. At Paddington, a barrel-vaulted concourse in pale concrete and white tiles creates a calm, column-free space beneath one of London's busiest transport hubs.", key_design_moves: ["Barrel-vaulted concrete shell — column-free platform and concourse", "Consistent pale material palette across all 10 new central stations", "Wayfinding integrated into architecture — not signage bolted on"], materials: ["Pale concrete", "White tiles", "Steel", "Glass"], site_strategy: "New deep-level station inserted beneath the existing Paddington Network Rail station, providing cross-London east-west connectivity from Reading to Shenfield.", program: "Platforms, ticketing hall, concourse, interchange with existing rail network", awards: "RIBA Stirling Prize 2024", tags: ["elizabeth line", "london", "grimshaw", "underground", "vault", "RIBA"], drawings: "Published technical drawings — Archdaily and TfL", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Elizabeth+Line+Grimshaw" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=Elizabeth+Line" }, { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Elizabeth_line" }], wiki: "Elizabeth_line", last_updated: "2025-01-15" },
  { id: 18, category: "Metro Station", name: "Saint-Denis Pleyel Station", architect: "Kengo Kuma and Associates", year: "2024", location: "Paris, France", typology: "Metro / RER Station", style: "Contemporary / Biophilic", units: "N/A", total_area: "18,000 sqm", floors: "B2 + Ground", concept: "The station is wrapped in a vertical timber louvre facade that softens its industrial context in Saint-Denis. The louvres reference the musical heritage of the nearby Pleyel concert hall while providing solar shading and creating a warm, distinctive identity.", key_design_moves: ["Vertical timber louvre facade as primary identity element", "Louvres oriented to filter western solar exposure", "Warm material palette contrasts with industrial neighbourhood context"], materials: ["Timber louvres", "Concrete", "Glass", "Steel"], site_strategy: "Part of the Grand Paris Express — the largest metro expansion in Europe. Saint-Denis Pleyel is a major interchange hub connecting four metro and RER lines.", program: "Major interchange station — platforms for 4 lines, concourse, ticketing, retail", awards: "Part of Grand Paris Express 2024", tags: ["kengo kuma", "paris", "timber", "grand paris", "biophilic", "interchange"], drawings: "Facade details and floor plans on Dezeen and Archdaily", sources: [{ label: "Dezeen", url: "https://www.dezeen.com/?s=Saint-Denis+Pleyel+Station+Kengo+Kuma" }, { label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Saint+Denis+Pleyel+Station" }, { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Saint-Denis%E2%80%93Pleyel_station" }], wiki: "Saint-Denis%E2%80%93Pleyel_station", last_updated: "2025-01-15" },
  { id: 19, category: "Metro Station", name: "Doha Metro — Al Riffa Station", architect: "UNStudio", year: "2019", location: "Doha, Qatar", typology: "Elevated Metro Station", style: "Parametric / Contemporary", units: "N/A", total_area: "8,500 sqm", floors: "3", concept: "UNStudio developed a unified design language across multiple Doha Metro stations, using parametric geometry to create distinctive canopy structures that respond to the desert climate. Each station skin provides shading while expressing dynamic movement through fluid, directional forms.", key_design_moves: ["Parametric canopy provides solar shading while expressing movement", "Interior geometry continuous from exterior — no applied decoration", "Consistent design language across multiple stations on the Gold Line"], materials: ["Aluminium composite panels", "Steel structure", "Glass", "Concrete"], site_strategy: "Part of Qatar's Integrated Railway Project — 37 stations across three metro lines constructed in preparation for FIFA 2022.", program: "Concourse, platforms, ticketing, passenger facilities, interchange connections", awards: "Qatar Integrated Railway Project — RIBA Award Shortlisted 2019", tags: ["UNStudio", "doha", "qatar", "parametric", "elevated", "canopy", "desert"], drawings: "Canopy details and plans on Archdaily", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Doha+Metro+UNStudio" }, { label: "UNStudio", url: "https://www.unstudio.com/en/page/13054/al-riffa-metro-station" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=Doha+Metro+UNStudio" }], wiki: "Doha_Metro", last_updated: "2025-01-15" },
  { id: 20, category: "Metro Station", name: "Villejuif Gustave Roussy Station", architect: "Dominique Perrault Architecture", year: "2024", location: "Villejuif, France", typology: "Underground Metro Station", style: "Contemporary / Landscape-Integrated", units: "N/A", total_area: "10,000 sqm", floors: "B3 + Ground", concept: "The station is sunken into the ground with no conventional facade — the architecture disappears below street level, opening the sky above the platforms 50 metres below. Natural light pours through the incision in the urban surface, making the station feel connected to the city above.", key_design_moves: ["Station carved into ground — no above-ground volume", "Natural light channelled 50m underground via open trench section", "Infrastructure exposed as architecture — raw concrete as finish"], materials: ["Raw concrete", "Glass", "Steel", "Stone paving"], site_strategy: "Part of the Grand Paris Express Line 14 extension. The station serves the Gustave Roussy cancer research campus, and its landscape integration creates a new public space at ground level.", program: "Platforms, concourse, ticketing, public plaza at ground level", awards: "Grand Paris Express 2024", tags: ["perrault", "paris", "underground", "landscape", "grand paris", "natural light"], drawings: "Section and plan drawings on Archdaily and Divisare", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Villejuif+Gustave+Roussy+Station" }, { label: "Divisare", url: "https://divisare.com/search?q=Perrault+Metro+Villejuif" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=Villejuif+Gustave+Roussy" }], wiki: "Dominique_Perrault", last_updated: "2025-01-15" },
  { id: 21, category: "Metro Station", name: "Monte Sant Angelo Station", architect: "AL_A / Anish Kapoor", year: "2024", location: "Naples, Italy", typology: "Underground Metro Station", style: "Contemporary / Sculptural", units: "N/A", total_area: "5,000 sqm", floors: "B2", concept: "Curved panels of weathering Corten steel swaddle the entrance of this Naples metro station, designed by Amanda Levete's AL_A in collaboration with sculptor Anish Kapoor. The exterior reads as a folded landscape erupting from the ground — a piece of sculpture that happens to be a station.", key_design_moves: ["Corten steel entrance as sculptural landmark", "Collaboration between architect and sculptor — no separation of art and building", "Weathering material ages and integrates with urban context over time"], materials: ["Corten weathering steel", "Concrete", "Glass", "Stone"], site_strategy: "Part of Naples' celebrated Art Stations programme, in which each station is a collaboration between a world-class architect and artist, transforming transit infrastructure into cultural destinations.", program: "Entrance pavilion, concourse, platforms, integrated artwork", awards: "Part of Naples Art Stations Programme", tags: ["AL_A", "Anish Kapoor", "naples", "corten", "sculptural", "art station"], drawings: "Facade details on Dezeen and e-architect", sources: [{ label: "Dezeen", url: "https://www.dezeen.com/?s=Monte+Sant+Angelo+Station+Naples" }, { label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Monte+Sant+Angelo+Station" }, { label: "e-architect", url: "https://www.e-architect.com/italy/monte-s-angelo-metro-station-naples" }], wiki: "Naples_Metro", last_updated: "2025-01-15" },
  { id: 22, category: "Metro Station", name: "Melbourne Metro Tunnel Stations", architect: "RSHP / Hassell / WW+P", year: "2023", location: "Melbourne, Australia", typology: "Underground Metro Station", style: "Contemporary / Robust", units: "N/A", total_area: "Various", floors: "B4", concept: "Five new underground stations were designed with a consistent architectural family language — robust materials, generous proportions, and strong wayfinding — intended to provide calm, dignified spaces for Melbourne's growing passenger demand.", key_design_moves: ["Consistent material and spatial language across 5 new stations", "Platform screen doors integrated into overall architectural composition", "Precast concrete elements standardised for efficiency and quality"], materials: ["Precast concrete", "Brick", "Steel", "Glass"], site_strategy: "New 9km underground rail corridor through Melbourne's CBD, connecting the existing Sunbury and Cranbourne/Pakenham lines through five new central-city stations.", program: "5 stations — platforms, concourses, entrances, interchange connections", awards: "Not Available", tags: ["RSHP", "melbourne", "australia", "underground", "precast", "family language"], drawings: "Plans and sections on Archdaily", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Melbourne+Metro+Tunnel+Stations" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=Melbourne+Metro+Tunnel" }, { label: "RSHP", url: "https://www.rshp.com/projects/transport/melbourne-metro-tunnel" }], wiki: "Melbourne_Airport_rail_link", last_updated: "2025-01-15" },
  { id: 23, category: "Metro Station", name: "Dubai Metro — Burj Khalifa Station", architect: "Wilkinson Eyre / Aedas", year: "2010", location: "Dubai, UAE", typology: "Elevated Metro Station", style: "Contemporary / Iconic", units: "N/A", total_area: "Various", floors: "3", concept: "The Dubai Metro elevated stations were designed as a consistent family of iconic forms — each station a distinctive steel and glass canopy that marks its location along Sheikh Zayed Road while providing shade and wayfinding in Dubai's extreme climate.", key_design_moves: ["Distinctive canopy forms as urban landmarks along SZR", "Climate-controlled enclosed platform for extreme heat conditions", "Lightweight steel and glass construction minimises visual mass"], materials: ["Structural steel", "Glass", "Aluminium cladding", "Concrete columns"], site_strategy: "Elevated guideway along Sheikh Zayed Road — stations positioned as landmarks at key urban nodes including the Burj Khalifa, Mall of the Emirates, and major business districts.", program: "Platform, concourse, ticketing, retail, interchange connections", awards: "Cityscape Dubai Award 2010", tags: ["dubai", "elevated", "UAE", "iconic", "climate", "canopy", "sheikh zayed road"], drawings: "Elevation and section drawings available on e-architect", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Dubai+Metro+Station" }, { label: "e-architect", url: "https://www.e-architect.com/dubai/dubai-metro" }, { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Dubai_Metro" }], wiki: "Dubai_Metro", last_updated: "2025-01-15" },
  { id: 24, category: "Metro Station", name: "Lisbon Metro — Oriente Station", architect: "Santiago Calatrava", year: "1998", location: "Lisbon, Portugal", typology: "Rail / Metro Station", style: "Structural Expressionism", units: "N/A", total_area: "78,000 sqm", floors: "Multiple", concept: "Designed for Expo 98, Oriente Station is Calatrava's most ambitious transport project — a vast steel tree canopy covers the surface platforms while the lower levels descend through layered concrete vaults housing the metro, suburban rail, and bus interchange.", key_design_moves: ["Steel tree canopy over surface rail platforms — organic structural form", "Multi-modal interchange — metro, rail, bus in single building", "Concrete vaulted galleries at lower levels create monumental interior scale"], materials: ["Steel tree structure", "Glass roof panels", "Reinforced concrete vaults", "Stone paving"], site_strategy: "Gateway station for Expo 98 on Lisbon's eastern waterfront, designed to handle 160,000 passengers daily while serving as the main arrival point for the World's Fair.", program: "Metro, suburban rail, high-speed rail, bus interchange — full multi-modal hub", awards: "European Union Prize for Contemporary Architecture 1998", tags: ["calatrava", "lisbon", "tree structure", "expo", "multi-modal", "landmark"], drawings: "Structural drawings and sections published by Calatrava office", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Oriente+Station+Calatrava+Lisbon" }, { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Lisbon_Oriente_station" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=Oriente+Station+Lisbon" }], wiki: "Lisbon_Oriente_station", last_updated: "2025-01-15" },
  { id: 25, category: "Metro Station", name: "Shenzhen Metro — Coastal Station", architect: "Chetwoods + J&A", year: "2024", location: "Shenzhen, China", typology: "Elevated Metro Station", style: "Contemporary / Themed", units: "N/A", total_area: "6,500 sqm", floors: "3", concept: "A coastal-themed transit hub that draws on Shenzhen's local landscape and cultural identity. Wave-form ceilings and marine material references transform the station interior into an immersive environment that reflects the city's relationship with the sea.", key_design_moves: ["Wave-form ceiling as primary interior design element", "Material palette references coastal landscape — blues, whites, textures", "Wayfinding embedded in environmental narrative of the station"], materials: ["GRC panels", "Glass", "Steel", "Coastal-toned finishes"], site_strategy: "Located in Shenzhen's coastal district, the station design is tailored to its specific urban and cultural context — reflecting the local landscape as part of a city-wide effort to give each metro station a distinct identity.", program: "Platforms, concourse, ticketing, retail, outdoor connection to waterfront", awards: "Not Available", tags: ["shenzhen", "china", "coastal", "themed", "contemporary", "elevated"], drawings: "Interior elevations on Dezeen", sources: [{ label: "Dezeen", url: "https://www.dezeen.com/?s=Shenzhen+Metro+Chetwoods" }, { label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Shenzhen+Metro+Station+Coastal" }], wiki: "Shenzhen_Metro", last_updated: "2025-01-15" },
  { id: 26, category: "Metro Station", name: "Copenhagen Metro — Cityringen Stations", architect: "Arup / Gottlieb Paludan", year: "2019", location: "Copenhagen, Denmark", typology: "Underground Metro Station", style: "Contemporary / Minimalist", units: "N/A", total_area: "Various", floors: "B3", concept: "The 17 new Cityringen stations share a consistent minimalist design language — white tile, natural light from above, and uncluttered platforms. The system is driverless and fully automated, so the architecture prioritises passenger experience over operational infrastructure.", key_design_moves: ["Skylights draw natural light 15m below street level", "Consistent minimalist white tile palette across all 17 stations", "Driverless operation — no driver cab — allows platform-length glazing"], materials: ["White ceramic tile", "Concrete", "Glass skylights", "Steel"], site_strategy: "17 new stations on a circular underground loop through Copenhagen's central districts, connecting previously underserved neighbourhoods to the existing metro network.", program: "17 stations — platforms, concourses, automated ticketing, cycle parking", awards: "Not Available", tags: ["copenhagen", "minimalist", "driverless", "skylight", "nordic", "white tile"], drawings: "Section drawings and plans on Archdaily", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Copenhagen+Metro+Cityringen" }, { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Cityringen" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=Copenhagen+Metro+Cityringen" }], wiki: "Cityringen", last_updated: "2025-01-15" },
  { id: 27, category: "Metro Station", name: "Jahad Metro Plaza", architect: "KA Architecture Studio", year: "2023", location: "Tehran, Iran", typology: "Metro Station + Public Space", style: "Contemporary / Brick", units: "N/A", total_area: "8,000 sqm", floors: "B1 + Ground", concept: "A cluster of brick barrel vaults crowns the station entrance, creating a new covered public plaza that is simultaneously a civic space and transit gateway. The brick vaulting references Persian architectural heritage while creating a practical shading structure for Tehran's climate.", key_design_moves: ["Brick barrel vaults create covered public plaza", "Persian vaulting tradition reinterpreted in contemporary transit context", "Station entrance integrated into urban plaza — not isolated as separate object"], materials: ["Brick", "Concrete", "Steel", "Stone paving"], site_strategy: "The station is embedded within a new public plaza, transforming the transit infrastructure into a civic amenity. The project demonstrates how metro stations can act as catalysts for urban public space.", program: "Metro entrance, concourse, covered public plaza, retail, landscaping", awards: "Not Available", tags: ["tehran", "brick", "barrel vault", "public space", "persian", "iran"], drawings: "Plans and vault details on Dezeen and Archdaily", sources: [{ label: "Dezeen", url: "https://www.dezeen.com/?s=Jahad+Metro+Plaza+Tehran" }, { label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Jahad+Metro+Plaza+Tehran" }], wiki: "Tehran_Metro", last_updated: "2025-01-15" },
  { id: 28, category: "Metro Station", name: "Santiago Metro — Line 6 Stations", architect: "IDOM", year: "2017", location: "Santiago, Chile", typology: "Underground Metro Station", style: "Contemporary / Robust", units: "N/A", total_area: "Various", floors: "B2", concept: "IDOM designed 10 new stations for Santiago's Line 6 with a shared design language emphasising structural clarity, natural ventilation strategies, and robust materials suited to high passenger volumes and Chile's seismic conditions.", key_design_moves: ["Seismic isolation integrated into structural and architectural design", "Natural ventilation strategy reduces mechanical system load", "Robust precast concrete finishes designed for high passenger wear"], materials: ["Precast concrete", "Steel", "Glass", "Ceramic tile"], site_strategy: "10 new stations connecting southern residential districts of Santiago with the city centre, designed to be robust, maintainable, and spatially legible for high daily passenger volumes.", program: "10 stations — platforms, concourses, ticketing, interchange connections", awards: "Not Available", tags: ["santiago", "chile", "seismic", "line 6", "robust", "precast", "IDOM"], drawings: "Plans and sections on Divisare and Archdaily", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Santiago+Metro+Line+6+IDOM" }, { label: "Divisare", url: "https://divisare.com/search?q=IDOM+Santiago+Metro" }, { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Line_6_(Santiago_Metro)" }], wiki: "Line_6_(Santiago_Metro)", last_updated: "2025-01-15" },
  { id: 29, category: "Metro Station", name: "Dnipro Metro Stations", architect: "Zaha Hadid Architects", year: "2025", location: "Dnipro, Ukraine", typology: "Underground Metro Station", style: "Parametric / Contemporary", units: "N/A", total_area: "Various", floors: "B3", concept: "Three new metro stations for Dnipro's network — Teatralna, Tsentralna, and Muzeina — designed by ZHA as a continuous architectural family of flowing concrete forms that connect the city's residential, cultural, and academic districts with its centre.", key_design_moves: ["Continuous flowing concrete interior — no separate wall and ceiling", "Three stations share one design language but each has distinct identity", "Cultural programme embedded in station interiors — murals and art"], materials: ["White concrete", "Glass", "Steel", "Backlit panels"], site_strategy: "Three interconnected stations on Dnipro's extended metro line, designed to connect the city's east with its cultural and commercial centre, replacing a section of the network interrupted by construction in 2016.", program: "3 stations — platforms, concourses, ticketing, cultural installations", awards: "Under construction as of 2025", tags: ["ZHA", "ukraine", "dnipro", "parametric", "flowing", "concrete", "cultural"], drawings: "Renderings and section sketches on Archdaily and ZHA website", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Dnipro+Metro+Stations+Zaha+Hadid" }, { label: "ZHA", url: "https://www.zaha-hadid.com/architecture/dnipro-metro-stations/" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=Dnipro+Metro+Zaha+Hadid" }], wiki: "Dnipro_Metro", last_updated: "2025-01-15" },
  { id: 30, category: "Metro Station", name: "Sydney Metro Central Station", architect: "Woods Bagot + John McAslan", year: "2024", location: "Sydney, Australia", typology: "Underground Metro Station", style: "Contemporary / Heritage-Integrated", units: "N/A", total_area: "Various", floors: "B3 + Ground", concept: "A new underground metro station inserted beneath Sydney's historic Central Station — one of Australia's most significant heritage buildings. The design respects the existing fabric while inserting a contemporary underground world that connects the old station with the new city metro network.", key_design_moves: ["New underground station connects to existing heritage rail station", "Material palette responds to sandstone and brick of existing station", "Passenger circulation designed to activate heritage concourse above"], materials: ["Sandstone-toned concrete", "Bronze steel", "Glass", "Brick"], site_strategy: "Deep underground station below Sydney's historic Central Station precinct, connecting the new Metro Southwest line with the existing surface rail network at one of the city's most important transport interchanges.", program: "Deep-level platforms, concourse, ticketing, interchange with surface rail", awards: "Not Available", tags: ["sydney", "australia", "heritage", "underground", "woods bagot", "McAslan"], drawings: "Plans and sections on Archdaily", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Sydney+Metro+Central+Station" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=Sydney+Metro+Central+Station" }, { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Sydney_Metro" }], wiki: "Sydney_Metro", last_updated: "2025-01-15" },
];
  { id: 31, category: "Metro Station", name: "Wuyuanwan Subway Station Renovation", architect: "ATENO (Troy Sun)", year: "2023", location: "Xiamen, China", typology: "Underground Metro Station", style: "Contemporary / Cultural", units: "N/A", total_area: "471 sqm", floors: "B2", concept: "A theatrical renovation of an existing subway station entrance, inspired by the disappearing red brick Minnan architecture of Fujian province. Undulating 3D-formed red concrete panels recreate the memory of traditional village houses in a contemporary transit context, transforming the entrance into a cultural and sculptural urban node.", key_design_moves: ["3D-formed red concrete panels reference Minnan brick architecture", "Undulating walls and curved corners create sculptural entrance volume", "Artist Su Wu mask sculptures integrated into wall insets"], materials: ["Red fair-faced concrete panels", "Metallic ceiling panels", "Strip floor lighting", "Glass doors"], site_strategy: "Renovation of Exit 3 of an existing station on Xiamen Metro Lines 2 and 3, transforming a neglected transit entrance into a cultural landmark that reconnects the bay area to its architectural heritage.", program: "Subway entrance, escalator and stair hall, integrated artwork, advertisement insets", awards: "Not Available", tags: ["renovation", "china", "xiamen", "cultural", "red concrete", "sculptural", "minnan"], drawings: "Interior elevations, wall panel details, and section drawings on Archdaily (archdaily.com/1015000)", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Wuyuanwan+Subway+Station+ATENO" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=Wuyuanwan+subway+station" }], wiki: "Xiamen_Metro", last_updated: "2025-01-20" },
  { id: 32, category: "Metro Station", name: "Metropolitan Station Lublin", architect: "Tremend Architecture Studio", year: "2024", location: "Lublin, Poland", typology: "Multi-Modal Transit Hub", style: "Contemporary / Sustainable", units: "N/A", total_area: "12,000 sqm", floors: "2 + Roof + B1", concept: "A modernist glazed pavilion whose organic latticed steel tree-columns support a dramatic canopy roof, creating an air of lightness over the main transport hub of Lublin. The station is one of Poland's most sustainable public buildings — a 'box in a box' glazed facade, solar canopy, vertical garden, and greywater harvesting system are integrated throughout.", key_design_moves: ["Organic latticed steel tree-columns as primary structural and aesthetic element", "'Box in a box' glazed facade system minimises energy consumption", "Solar PV integrated into smart bus shelter canopy across 43 bus stands", "300 sqm vertical garden on exterior facade reduces urban heat island effect"], materials: ["Stainless steel latticed columns", "Glazed facades", "Low-emissivity concrete", "Photovoltaic glass canopy panels"], site_strategy: "Located adjacent to the listed 19th-century Lublin Central Railway Station, the new Metropolitan Station creates a contemporary contrast to the historic eclectic building while anchoring the Integrated Transportation Centre connecting urban, regional and national networks.", program: "43 bus stands, railway platforms, underground car park with EV charging, cycle parking, public roof garden, waiting rooms, cafe", awards: "World Architecture Festival — Transport Category Winner 2024", tags: ["poland", "sustainable", "lublin", "WAF winner", "tree columns", "multi-modal", "green roof"], drawings: "Plans, sections, facade details, and column details on Archdaily and Divisare", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Metropolitan+Station+Lublin+Tremend" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=Metropolitan+Station+Lublin" }, { label: "Divisare", url: "https://divisare.com/search?q=Tremend+Metropolitan+Station+Lublin" }], wiki: "Lublin", last_updated: "2025-01-20" },
  { id: 33, category: "Metro Station", name: "Mumbai Metro Lines 2A & 7", architect: "Studio Archohm", year: "2022", location: "Mumbai, India", typology: "Elevated Metro Station", style: "Contemporary / Systematic", units: "N/A", total_area: "Various — 40+ stations", floors: "Elevated", concept: "A design system rather than a single building — Archohm conceived a 'kit of parts' for 40+ elevated metro stations across Mumbai's Lines 2A and 7, balancing city-wide visual coherence with site-specific identity. Vertical aluminium louvres form the primary facade treatment, providing solar and rain protection while creating a monolithic, dynamic box that reads as infrastructure rather than decoration.", key_design_moves: ["Vertical aluminium louvre system — unified language across 40+ stations", "All utilities, lights, and pipes concealed behind louvred facade", "Colour-coded columns and viaducts serve as city-level wayfinding", "Context-specific art and graphics give each station local identity"], materials: ["Aluminium vertical louvres", "Glass", "Concrete structure", "Salt and humidity resistant finishes"], site_strategy: "Two elevated metro lines running parallel to Western Express Highway and S.V. Road through Mumbai's dense western suburbs, designed to relieve road and train congestion by up to one third.", program: "40+ elevated stations — platform, concourse, ticketing, accessible lifts, station-specific public art", awards: "Not Available", tags: ["mumbai", "india", "elevated", "systematic", "louvres", "kit of parts", "archohm"], drawings: "Facade system drawings, louvre detail sections, and platform plans on Archdaily and Archohm website", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Mumbai+Metro+Archohm" }, { label: "Archohm", url: "https://www.archohm.com/projects/mumbai-stations.html" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=Mumbai+Metro+Archohm" }], wiki: "Mumbai_Metro", last_updated: "2025-01-20" },
  { id: 34, category: "Metro Station", name: "Brent Cross West Station — The Arbour", architect: "Studio Egret West / shedkm", year: "2023", location: "London, United Kingdom", typology: "Mainline Rail Station", style: "Contemporary / Biophilic / Timber", units: "N/A", total_area: "874 sqm (entrance building)", floors: "3 levels", concept: "The Arbour is the eastern entrance to London's first new mainline station in over a decade — a 13m high glulam larch timber canopy with hanging planters cascading from its structure, creating a 'living gateway' into the Brent Cross Town neighbourhood. The timber frame contains 150m3 of larch glulam with no embedded steelwork except at connections — structural simplicity as architectural expression.", key_design_moves: ["13m cantilevered glulam larch canopy — 150m3 of timber, 75 tonnes", "Hanging planters cascade from canopy structure — landscape drawn into building", "Canopy sits on single offset column line — preserving clear pedestrian route and vista", "250sqm vitreous enamel public art frieze integrated into concourse"], materials: ["Larch glulam (820mm x 720mm columns)", "Glazed canopy panels", "Low-carbon concrete", "Vitreous enamel art panels"], site_strategy: "Eastern entrance to a new Thameslink station catalysing the Brent Cross Town regeneration — 7,500 new homes and 25,000 jobs. The station connects the new neighbourhood to central London in under 12 minutes.", program: "Entrance hall, escalators and lifts to overbridge, 68 cycle parking spaces, public art installation, connection to Station Square", awards: "First major new mainline station in London in over a decade", tags: ["london", "timber", "glulam", "biophilic", "canopy", "regeneration", "mainline"], drawings: "Structural canopy details, glulam connection drawings, and section on Architects Journal and Studio Egret West website", sources: [{ label: "Architects Journal", url: "https://www.architectsjournal.co.uk/buildings/shedkm-and-studio-egret-west-complete-station-entrance-for-brent-cross-west" }, { label: "Archello", url: "https://archello.com/news/lofty-timber-canopy-welcomes-commuters-at-new-brent-cross-west-station" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=Brent+Cross+West+station" }], wiki: "Brent_Cross_West_railway_station", last_updated: "2025-01-20" },
  { id: 35, category: "Metro Station", name: "Qasr AlHokm Metro Station", architect: "Snøhetta", year: "2025", location: "Riyadh, Saudi Arabia", typology: "Underground Metro Station", style: "Contemporary / Biophilic", units: "N/A", total_area: "12,000 sqm", floors: "B3 + Ground", concept: "A 360-degree reflective mirrored bowl canopy at street level dissolves the boundary between the station and its surroundings, making the entrance almost invisible while drawing sky and city into its surface. Below, a lush underground garden atrium — rare in the Saudi capital — provides a biophilic antidote to the urban desert environment.", key_design_moves: ["360-degree reflective canopy — station disappears into sky reflection", "Underground planted atrium — biophilic space 15m below street", "Geometry derived from traditional muqarnas vaulting — cultural reference abstracted into contemporary form", "Canopy structure casts dappled light shadow patterns onto concourse below"], materials: ["Mirrored stainless steel canopy", "Stone paving", "Concrete", "Planted walls and ceiling", "Water feature"], site_strategy: "Located adjacent to the historic Qasr AlHokm Palace complex in Riyadh's historic centre — the station's material restraint and cultural references respond to the significance of its context while serving as one of four major interchange hubs on the Riyadh Metro.", program: "Underground platforms, concourse, ticketing, planted atrium, street-level mirrored canopy pavilion", awards: "Completed 2025 — part of Riyadh Metro network", tags: ["snohetta", "riyadh", "saudi", "mirrored", "biophilic", "underground garden", "muqarnas"], drawings: "Section drawings, canopy geometry, and atrium details on Archdaily and Snohetta website", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Qasr+AlHokm+Metro+Station+Snohetta" }, { label: "Snohetta", url: "https://snohetta.com/projects/qasr-alhokm-metro-station" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=Qasr+AlHokm+Metro+Station" }], wiki: "Riyadh_Metro", last_updated: "2025-02-01" },
  { id: 36, category: "Metro Station", name: "Auckland City Rail Link Stations", architect: "Grimshaw Architects", year: "2025", location: "Auckland, New Zealand", typology: "Underground Metro Station", style: "Contemporary / Cultural", units: "N/A", total_area: "Various", floors: "B3", concept: "The City Rail Link transforms Auckland's existing Britomart surface terminus into a through-running underground rail network. Grimshaw's station designs integrate Māori cultural motifs into the architecture — patterned concrete walls reference woven flax and tukutuku panels, embedding indigenous identity into the infrastructure of New Zealand's largest city.", key_design_moves: ["Māori cultural motifs cast into concrete wall and ceiling panels", "Station cavern geometry maximises natural acoustic quality", "Wayfinding integrated into material pattern — not signage overlay", "Heritage surface buildings preserved and connected to new underground concourses"], materials: ["Patterned precast concrete", "Steel", "Glass", "Terrazzo flooring"], site_strategy: "3.45km underground tunnel loop connecting Britomart to Mount Eden through two new stations — Aotea and Karangahape — transforming the existing terminus into a through-line and unlocking capacity across the entire Auckland rail network.", program: "2 new underground stations, extended Britomart interchange, concourses, platforms, integrated public art", awards: "Not Available — opened 2025", tags: ["auckland", "new zealand", "maori", "cultural", "underground", "grimshaw", "city rail link"], drawings: "Cultural motif drawings and station sections on Grimshaw website", sources: [{ label: "Grimshaw", url: "https://grimshaw.global/projects/city-rail-link/" }, { label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Auckland+City+Rail+Link+Grimshaw" }, { label: "Dezeen", url: "https://www.dezeen.com/?s=Auckland+City+Rail+Link" }], wiki: "City_Rail_Link", last_updated: "2025-02-01" },
  { id: 37, category: "Metro Station", name: "Grand Paris Express — Arcueil-Cachan Station", architect: "AREP", year: "2024", location: "Arcueil, France", typology: "Underground Metro Station", style: "Contemporary / Urban Integration", units: "N/A", total_area: "8,000 sqm", floors: "B2 + Ground", concept: "One of 68 new stations on the Grand Paris Express — the largest public transport infrastructure project in Europe. AREP designed this station as a permeable public space rather than a closed transit box, with a large glazed canopy creating a covered urban threshold that draws the station into the life of its surrounding neighbourhood.", key_design_moves: ["Large glazed street-level canopy creates covered urban public space", "Station layout designed for maximum permeability — not a closed box", "Robust material palette designed for 50-year service life without maintenance", "Landmark entrance creates local identity anchor in residential neighbourhood"], materials: ["Concrete", "Steel structure", "Large glazed canopy", "Natural stone paving"], site_strategy: "Part of Grand Paris Express Line 15 South — a major new orbital metro connecting Paris suburbs without passing through the city centre, serving 150,000 passengers daily once complete.", program: "Underground platforms, concourse, ticketing, covered public plaza, cycle parking, bus interchange", awards: "Part of Grand Paris Express 2024", tags: ["paris", "grand paris express", "AREP", "urban integration", "glazed canopy", "orbital metro"], drawings: "Station plans, sections, and canopy details on AREP and Grand Paris Express websites", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Grand+Paris+Express+Arcueil+Cachan" }, { label: "Grand Paris Express", url: "https://www.societedugrandparis.fr/gpe/ligne/ligne-15-sud" }], wiki: "Grand_Paris_Express", last_updated: "2025-02-01" },
  { id: 38, category: "Metro Station", name: "Coburg and Moreland Stations", architect: "Wood Marsh Architecture", year: "2023", location: "Melbourne, Australia", typology: "Surface Metro Station", style: "Contemporary / Civic", units: "N/A", total_area: "Various", floors: "Ground + Platform", concept: "Wood Marsh's two new suburban metro stations for the Melbourne Suburban Rail Loop adopt a civic architectural approach — robust brick and concrete structures with generous canopied platforms that reference the materiality of their suburban Melbourne context rather than imposing generic infrastructure aesthetics.", key_design_moves: ["Brick facades reference materiality of suburban Melbourne neighbourhood context", "Generous platform canopy designed for Melbourne's variable weather", "Civic public space at station entrance — not just drop-off and ticketing", "Platform edge detail designed for full accessibility with platform screen doors"], materials: ["Brick", "Concrete", "Steel canopy structure", "Glass screens"], site_strategy: "Two stations on Melbourne's new Suburban Rail Loop — an orbital rail network under construction in Melbourne's middle suburbs, connecting activity centres without requiring travel through the CBD.", program: "Platform, concourse, ticketing, public plaza, cycle parking, bus interchange", awards: "Not Available", tags: ["melbourne", "australia", "civic", "brick", "suburban", "Wood Marsh", "orbital"], drawings: "Elevation and section drawings on Archdaily and Wood Marsh website", sources: [{ label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Coburg+Moreland+Station+Wood+Marsh" }, { label: "Archello", url: "https://archello.com/search?q=Wood+Marsh+metro+station" }], wiki: "Suburban_Rail_Loop", last_updated: "2025-02-01" },
  { id: 39, category: "Metro Station", name: "Gare de Mons", architect: "Santiago Calatrava", year: "2025", location: "Mons, Belgium", typology: "Rail Station", style: "Structural Expressionism", units: "N/A", total_area: "20,000 sqm", floors: "Multiple", concept: "Calatrava's new station for Mons, Belgium features his signature branching white steel rib structure, creating a cathedral-like platform hall of extraordinary scale. The rhythmic repetition of the structural form produces a dynamic light-and-shadow environment that transforms the daily act of catching a train.", key_design_moves: ["Branching white steel ribs create vaulted platform hall", "Rhythm of structural form produces dynamic light and shadow", "Underground pedestrian connection to city centre integrated into station design", "Calatrava's signature vocabulary applied at the scale of a major European railway hub"], materials: ["White painted steel ribs", "Glass roof panels", "Concrete base structure", "White stone paving"], site_strategy: "Major new station for Mons serving high-speed and intercity services, designed as a gateway to a city that was European Capital of Culture in 2015.", program: "Multiple platforms, main hall, ticketing concourse, underground city connection, commercial spaces", awards: "Not Available — completed 2025", tags: ["calatrava", "belgium", "mons", "structural expressionism", "white steel", "vaulted"], drawings: "Structural rib sections and platform hall plans on Dezeen and Calatrava website", sources: [{ label: "Dezeen", url: "https://www.dezeen.com/?s=Gare+de+Mons+Calatrava" }, { label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Gare+de+Mons+Calatrava" }], wiki: "Mons_railway_station", last_updated: "2025-02-01" },
  { id: 40, category: "Metro Station", name: "Jahad Metro Plaza", architect: "KA Architecture Studio", year: "2023", location: "Tehran, Iran", typology: "Metro Station + Public Plaza", style: "Contemporary / Brick / Persian", units: "N/A", total_area: "8,000 sqm", floors: "B1 + Ground", concept: "A cluster of brick barrel vaults crowns this Tehran metro station entrance, creating a new covered public plaza that is simultaneously a civic space and transit gateway. The vaulting reinterprets Persian architectural heritage in a contemporary transit context, providing natural shade and a human-scaled canopy in one of the world's most congested cities.", key_design_moves: ["Cluster of brick barrel vaults create covered civic plaza over metro entrance", "Persian vaulting tradition reinterpreted in contemporary transit context — heritage without historicism", "Station entrance integrated into urban plaza — transit and public space are one", "Brick material ages and integrates with Tehran's existing urban fabric"], materials: ["Brick", "Concrete vault structure", "Steel", "Stone paving"], site_strategy: "The station is embedded within a new public plaza in Tehran's urban fabric, demonstrating how metro infrastructure can act as a catalyst for civic space creation rather than urban disruption.", program: "Metro entrance pavilion, concourse, barrel-vaulted public plaza, retail, landscaping", awards: "Not Available", tags: ["tehran", "iran", "brick", "barrel vault", "persian", "civic", "public space"], drawings: "Vault structural drawings, section through plaza, and plan on Dezeen and Archdaily", sources: [{ label: "Dezeen", url: "https://www.dezeen.com/?s=Jahad+Metro+Plaza+Tehran" }, { label: "Archdaily", url: "https://www.archdaily.com/search/projects?q=Jahad+Metro+Plaza+Tehran" }], wiki: "Tehran_Metro", last_updated: "2025-02-01" }

const ALL_TYPOLOGIES = ["All", ...new Set(PROJECTS.map(p => p.typology))];
const ALL_STYLES = ["All", ...new Set(PROJECTS.map(p => p.style.split(" / ")[0]))];
const YEARS = ["All", "Before 1980", "1980–2000", "2000–2010", "2010–present"];
const FALLBACK = "https://placehold.co/600x400/1a1a14/c8a96e?text=View+on+Archdaily";

function filterByYear(p, r) {
  const y = parseInt(p.year);
  if (r === "All") return true;
  if (r === "Before 1980") return y < 1980;
  if (r === "1980–2000") return y >= 1980 && y <= 2000;
  if (r === "2000–2010") return y >= 2000 && y <= 2010;
  if (r === "2010–present") return y > 2010;
  return true;
}

function useWikiImage(wikiTitle) {
  const [img, setImg] = useState(null);
  useEffect(() => {
    if (!wikiTitle) return;
    fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${wikiTitle}`)
      .then(r => r.json())
      .then(d => { if (d.thumbnail?.source) setImg(d.thumbnail.source); })
      .catch(() => {});
  }, [wikiTitle]);
  return img || FALLBACK;
}

function ProjectCard({ p, selected, onSelect, onFav, isFav }) {
  const img = useWikiImage(p.wiki);
  return (
    <div onClick={() => onSelect(p)} style={{ background: "#fff", border: selected ? "2px solid #1a1a14" : "1px solid #ddd8cc", cursor: "pointer", overflow: "hidden", transition: "box-shadow 0.15s" }}>
      <div style={{ height: "180px", overflow: "hidden", position: "relative", background: "#e8e4dc" }}>
        <img src={img} alt={p.name} style={{ width: "100%", height: "100%", objectFit: "cover" }} onError={e => { e.target.src = FALLBACK; }} />
        <button onClick={e => { e.stopPropagation(); onFav(p.id); }} style={{ position: "absolute", top: "10px", right: "10px", background: "rgba(255,255,255,0.9)", border: "none", width: "28px", height: "28px", cursor: "pointer", fontSize: "14px" }}>{isFav ? "★" : "☆"}</button>
        <div style={{ position: "absolute", bottom: "10px", left: "10px", background: "rgba(26,26,20,0.85)", color: "#f5f0e8", fontSize: "9px", letterSpacing: "2px", padding: "4px 8px", textTransform: "uppercase" }}>{p.typology}</div>
        <div style={{ position: "absolute", top: "10px", left: "10px", background: p.category === "Metro Station" ? "rgba(50,80,120,0.9)" : "rgba(80,60,20,0.9)", color: "#f5f0e8", fontSize: "8px", letterSpacing: "2px", padding: "3px 7px", textTransform: "uppercase" }}>{p.category}</div>
      </div>
      <div style={{ padding: "16px 18px 14px" }}>
        <div style={{ fontSize: "15px", marginBottom: "4px" }}>{p.name}</div>
        <div style={{ fontSize: "12px", color: "#8a8a7a", marginBottom: "10px" }}>{p.architect} · {p.year}</div>
        <div style={{ fontSize: "11px", color: "#aaa8a0", marginBottom: "12px", lineHeight: "1.6", display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical", overflow: "hidden" }}>{p.concept}</div>
        {p.drawings && p.drawings !== "N/A" && (
          <div style={{ fontSize: "10px", color: "#4a8a6a", marginBottom: "10px", letterSpacing: "0.5px" }}>📐 {p.drawings}</div>
        )}
        <div style={{ display: "flex", flexWrap: "wrap", gap: "4px", marginBottom: "12px" }}>
          {p.tags.slice(0, 3).map((t, i) => <span key={i} style={{ fontSize: "9px", letterSpacing: "1px", textTransform: "uppercase", padding: "2px 7px", border: "1px solid #ddd8cc", color: "#8a8a7a" }}>{t}</span>)}
        </div>
        <div style={{ borderTop: "1px solid #eee8e0", paddingTop: "10px", display: "flex", gap: "10px", flexWrap: "wrap" }}>
          {p.sources.map((s, i) => <a key={i} href={s.url} target="_blank" rel="noreferrer" onClick={e => e.stopPropagation()} style={{ color: "#c8a030", textDecoration: "none", fontSize: "10px" }}>↗ {s.label}</a>)}
        </div>
      </div>
    </div>
  );
}

function DetailPanel({ p, isFav, onFav, copied, onCopy, onDownload }) {
  const img = useWikiImage(p.wiki);
  return (
    <div style={{ width: "420px", flexShrink: 0, borderLeft: "1px solid #ddd8cc", background: "#fff", overflowY: "auto", position: "sticky", top: 0, maxHeight: "calc(100vh - 52px)" }}>
      <div style={{ height: "220px", overflow: "hidden", background: "#e8e4dc" }}>
        <img src={img} alt="" style={{ width: "100%", height: "100%", objectFit: "cover" }} onError={e => { e.target.src = FALLBACK; }} />
      </div>
      <div style={{ display: "flex", borderBottom: "1px solid #eee8e0" }}>
        {[{ label: copied ? "Copied!" : "Copy Data", action: onCopy }, { label: "Download", action: onDownload }, { label: isFav ? "★ Saved" : "☆ Save", action: () => onFav(p.id) }].map((btn, i) => (
          <button key={i} onClick={btn.action} style={{ flex: 1, padding: "10px 0", background: "transparent", border: "none", borderRight: i < 2 ? "1px solid #eee8e0" : "none", fontSize: "10px", letterSpacing: "2px", textTransform: "uppercase", color: "#8a8a7a", cursor: "pointer", fontFamily: "inherit" }}>{btn.label}</button>
        ))}
      </div>
      <div style={{ padding: "24px" }}>
        <div style={{ display: "flex", gap: "8px", marginBottom: "8px" }}>
          <span style={{ fontSize: "9px", letterSpacing: "2px", color: p.category === "Metro Station" ? "#3a6aaa" : "#c8a030", textTransform: "uppercase", padding: "3px 8px", border: `1px solid ${p.category === "Metro Station" ? "#3a6aaa" : "#c8a030"}` }}>{p.category}</span>
          <span style={{ fontSize: "9px", letterSpacing: "2px", color: "#aaa", textTransform: "uppercase" }}>{p.typology}</span>
        </div>
        <h2 style={{ margin: "0 0 6px", fontSize: "20px", fontWeight: "400", lineHeight: "1.3" }}>{p.name}</h2>
        <div style={{ fontSize: "13px", color: "#8a8a7a", marginBottom: "20px" }}>{p.architect} · {p.location} · {p.year}</div>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "1px", background: "#eee8e0", marginBottom: "24px" }}>
          {[{ l: "Units / Platforms", v: p.units }, { l: "Area", v: p.total_area }, { l: "Floors", v: p.floors }, { l: "Style", v: p.style.split(" / ")[0] }].map((s, i) => (
            <div key={i} style={{ background: "#fff", padding: "12px 14px" }}>
              <div style={{ fontSize: "9px", letterSpacing: "2px", color: "#aaa", textTransform: "uppercase", marginBottom: "4px" }}>{s.l}</div>
              <div style={{ fontSize: "13px" }}>{s.v}</div>
            </div>
          ))}
        </div>
        {p.drawings && p.drawings !== "N/A" && (
          <div style={{ marginBottom: "20px", padding: "12px 14px", background: "#f0f7f0", border: "1px solid #c0ddc0" }}>
            <div style={{ fontSize: "9px", letterSpacing: "3px", color: "#4a8a6a", textTransform: "uppercase", marginBottom: "6px" }}>Drawings Available</div>
            <p style={{ margin: 0, fontSize: "12px", lineHeight: "1.7", color: "#4a4a3a" }}>{p.drawings}</p>
          </div>
        )}
        {[{ title: "Concept", content: p.concept }, { title: "Site Strategy", content: p.site_strategy }, { title: "Program", content: p.program }, { title: "Awards", content: p.awards }].map(s => (
          <div key={s.title} style={{ marginBottom: "20px" }}>
            <div style={{ fontSize: "9px", letterSpacing: "3px", color: "#aaa", textTransform: "uppercase", marginBottom: "8px" }}>{s.title}</div>
            <p style={{ margin: 0, fontSize: "12px", lineHeight: "1.8", color: "#4a4a3a" }}>{s.content}</p>
          </div>
        ))}
        <div style={{ marginBottom: "20px" }}>
          <div style={{ fontSize: "9px", letterSpacing: "3px", color: "#aaa", textTransform: "uppercase", marginBottom: "10px" }}>Key Design Moves</div>
          {p.key_design_moves.map((m, i) => (
            <div key={i} style={{ display: "flex", gap: "10px", marginBottom: "8px" }}>
              <span style={{ fontSize: "11px", color: "#c8a030", flexShrink: 0 }}>0{i + 1}</span>
              <span style={{ fontSize: "12px", color: "#4a4a3a", lineHeight: "1.7" }}>{m}</span>
            </div>
          ))}
        </div>
        <div style={{ marginBottom: "20px" }}>
          <div style={{ fontSize: "9px", letterSpacing: "3px", color: "#aaa", textTransform: "uppercase", marginBottom: "10px" }}>Materials</div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "6px" }}>
            {p.materials.map((m, i) => <span key={i} style={{ fontSize: "10px", padding: "4px 10px", border: "1px solid #ddd8cc", color: "#6a6a5a" }}>{m}</span>)}
          </div>
        </div>
        <div style={{ marginBottom: "20px" }}>
          <div style={{ fontSize: "9px", letterSpacing: "3px", color: "#aaa", textTransform: "uppercase", marginBottom: "10px" }}>Tags</div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "6px" }}>
            {p.tags.map((t, i) => <span key={i} style={{ fontSize: "10px", padding: "4px 10px", background: "#f5f0e8", color: "#8a8a7a" }}>{t}</span>)}
          </div>
        </div>
        <div style={{ paddingTop: "16px", borderTop: "1px solid #eee8e0" }}>
          <div style={{ fontSize: "9px", letterSpacing: "3px", color: "#aaa", textTransform: "uppercase", marginBottom: "10px" }}>Sources</div>
          {p.sources.map((s, i) => <a key={i} href={s.url} target="_blank" rel="noreferrer" style={{ display: "block", fontSize: "11px", color: "#c8a030", marginBottom: "8px", textDecoration: "none" }}>↗ {s.label}</a>)}
        </div>
      </div>
    </div>
  );
}

export default function NArchRef() {
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("All");
  const [typology, setTypology] = useState("All");
  const [style, setStyle] = useState("All");
  const [year, setYear] = useState("All");
  const [selected, setSelected] = useState(null);
  const [favourites, setFavourites] = useState([]);
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState("all");

  const filteredTypologies = useMemo(() => {
    const base = category === "All" ? PROJECTS : PROJECTS.filter(p => p.category === category);
    return ["All", ...new Set(base.map(p => p.typology))];
  }, [category]);

  const filtered = useMemo(() => PROJECTS.filter(p => {
    const q = search.toLowerCase();
    return (!q || p.name.toLowerCase().includes(q) || p.architect.toLowerCase().includes(q) || p.concept.toLowerCase().includes(q) || p.tags.some(t => t.includes(q)))
      && (category === "All" || p.category === category)
      && (typology === "All" || p.typology === typology)
      && (style === "All" || p.style.includes(style))
      && filterByYear(p, year)
      && (activeTab !== "favourites" || favourites.includes(p.id));
  }), [search, category, typology, style, year, activeTab, favourites]);

  const toggleFav = (id) => setFavourites(f => f.includes(id) ? f.filter(x => x !== id) : [...f, id]);

  const copyData = () => {
    if (!selected) return;
    navigator.clipboard.writeText(JSON.stringify(selected, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadTxt = () => {
    if (!selected) return;
    const content = `NArch Reference\n${"=".repeat(50)}\n\nPROJECT: ${selected.name}\nCATEGORY: ${selected.category}\nARCHITECT: ${selected.architect}\nYEAR: ${selected.year}\nLOCATION: ${selected.location}\nTYPOLOGY: ${selected.typology}\nSTYLE: ${selected.style}\nFLOORS: ${selected.floors}\nTOTAL AREA: ${selected.total_area}\n\nCONCEPT\n${selected.concept}\n\nSITE STRATEGY\n${selected.site_strategy}\n\nKEY DESIGN MOVES\n${selected.key_design_moves.map((m, i) => `${i + 1}. ${m}`).join("\n")}\n\nMATERIALS\n${selected.materials.join(", ")}\n\nPROGRAM\n${selected.program}\n\nDRAWINGS\n${selected.drawings}\n\nAWARDS\n${selected.awards}\n\nSOURCES\n${selected.sources.map(s => `${s.label}: ${s.url}`).join("\n")}\n\nTAGS\n${selected.tags.join(", ")}`;
    const a = document.createElement("a");
    a.href = URL.createObjectURL(new Blob([content], { type: "text/plain" }));
    a.download = `NArchRef_${selected.name.replace(/\s+/g, "_")}.txt`;
    a.click();
  };

  const lastUpdated = "2025-02-01";
  const housingCount = PROJECTS.filter(p => p.category === "Housing").length;
  const metroCount = PROJECTS.filter(p => p.category === "Metro Station").length;

  return (
    <div style={{ fontFamily: "'Palatino Linotype', 'Book Antiqua', Palatino, serif", background: "#f5f0e8", minHeight: "100vh", color: "#1a1a14" }}>
      <div style={{ background: "#1a1a14", padding: "0 40px", display: "flex", alignItems: "center", justifyContent: "space-between", height: "52px" }}>
        <div style={{ display: "flex", alignItems: "baseline", gap: "12px" }}>
          <span style={{ fontSize: "18px", color: "#f5f0e8", letterSpacing: "3px" }}>NArch</span>
          <span style={{ fontSize: "10px", color: "#5a5a4a", letterSpacing: "3px", textTransform: "uppercase" }}>Reference</span>
        </div>
        <div style={{ display: "flex", gap: "24px", alignItems: "center" }}>
          <span style={{ fontSize: "10px", color: "#5a5a4a", letterSpacing: "1px" }}>Housing: {housingCount} · Metro: {metroCount}</span>
          <span style={{ fontSize: "10px", color: "#5a5a4a", letterSpacing: "2px" }}>UPDATED: {lastUpdated}</span>
        </div>
      </div>

      <div style={{ padding: "48px 40px 36px", borderBottom: "1px solid #ddd8cc", background: "linear-gradient(180deg, #ede8e0 0%, #f5f0e8 100%)" }}>
        <div style={{ maxWidth: "600px" }}>
          <h1 style={{ margin: "0 0 8px", fontSize: "40px", fontWeight: "400", letterSpacing: "-1px", lineHeight: "1.1" }}>NArch<br />Reference</h1>
          <p style={{ margin: "0 0 28px", fontSize: "14px", color: "#8a8a7a", lineHeight: "1.7", maxWidth: "480px" }}>Structured architectural data for students — concept, materials, program, and design moves from significant housing and metro station projects worldwide.</p>
          <div style={{ position: "relative", maxWidth: "520px" }}>
            <input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search by project, architect, concept, tag, or location..." style={{ width: "100%", padding: "14px 48px 14px 18px", border: "1px solid #ccc8bc", background: "#fff", fontSize: "13px", fontFamily: "inherit", color: "#1a1a14", outline: "none", boxSizing: "border-box" }} />
            <span style={{ position: "absolute", right: "16px", top: "50%", transform: "translateY(-50%)", color: "#aaa" }}>⌕</span>
          </div>
        </div>
      </div>

      <div style={{ padding: "16px 40px", borderBottom: "1px solid #ddd8cc", display: "flex", gap: "16px", alignItems: "center", flexWrap: "wrap", background: "#f5f0e8" }}>
        {/* Category filter — prominent */}
        <div style={{ display: "flex", gap: "0", marginRight: "8px" }}>
          {CATEGORIES.map(cat => (
            <button key={cat} onClick={() => { setCategory(cat); setTypology("All"); }} style={{ padding: "7px 18px", background: category === cat ? "#1a1a14" : "transparent", color: category === cat ? "#f5f0e8" : "#8a8a7a", border: "1px solid #ccc8bc", fontSize: "10px", letterSpacing: "2px", textTransform: "uppercase", cursor: "pointer", fontFamily: "inherit", marginLeft: "-1px" }}>{cat}</button>
          ))}
        </div>

        {[{ label: "Type", value: typology, set: setTypology, options: filteredTypologies }, { label: "Style", value: style, set: setStyle, options: ALL_STYLES }, { label: "Year", value: year, set: setYear, options: YEARS }].map(f => (
          <div key={f.label} style={{ display: "flex", alignItems: "center", gap: "8px" }}>
            <span style={{ fontSize: "10px", letterSpacing: "2px", color: "#8a8a7a", textTransform: "uppercase" }}>{f.label}</span>
            <select value={f.value} onChange={e => f.set(e.target.value)} style={{ padding: "6px 28px 6px 10px", border: "1px solid #ccc8bc", background: "#fff", fontSize: "12px", fontFamily: "inherit", color: "#1a1a14", cursor: "pointer", outline: "none", appearance: "none", backgroundImage: "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='10' height='6'%3E%3Cpath d='M0 0l5 6 5-6z' fill='%238a8a7a'/%3E%3C/svg%3E\")", backgroundRepeat: "no-repeat", backgroundPosition: "right 8px center" }}>
              {f.options.map(o => <option key={o}>{o}</option>)}
            </select>
          </div>
        ))}

        <div style={{ marginLeft: "auto", display: "flex" }}>
          {["all", "favourites"].map(tab => (
            <button key={tab} onClick={() => setActiveTab(tab)} style={{ padding: "6px 16px", background: activeTab === tab ? "#1a1a14" : "transparent", color: activeTab === tab ? "#f5f0e8" : "#8a8a7a", border: "1px solid #ccc8bc", fontSize: "10px", letterSpacing: "2px", textTransform: "uppercase", cursor: "pointer", fontFamily: "inherit", marginLeft: "-1px" }}>
              {tab === "favourites" ? `★ Saved (${favourites.length})` : `All (${PROJECTS.length})`}
            </button>
          ))}
        </div>
        <div style={{ fontSize: "11px", color: "#aaa8a0" }}>{filtered.length} result{filtered.length !== 1 ? "s" : ""}</div>
      </div>

      <div style={{ display: "flex", minHeight: "calc(100vh - 280px)" }}>
        <div style={{ flex: 1, padding: "32px 40px", display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: "24px", alignContent: "start" }}>
          {filtered.length === 0 ? (
            <div style={{ gridColumn: "1/-1", textAlign: "center", padding: "80px 0", color: "#aaa" }}>
              <div style={{ fontSize: "32px", marginBottom: "16px" }}>◻</div>
              <div style={{ fontSize: "12px", letterSpacing: "2px", textTransform: "uppercase" }}>No projects found</div>
            </div>
          ) : filtered.map(p => (
            <ProjectCard key={p.id} p={p} selected={selected?.id === p.id} onSelect={setSelected} onFav={toggleFav} isFav={favourites.includes(p.id)} />
          ))}
        </div>
        {selected && <DetailPanel p={selected} isFav={favourites.includes(selected.id)} onFav={toggleFav} copied={copied} onCopy={copyData} onDownload={downloadTxt} />}
      </div>
    </div>
  );
}
